package mybatis.bean;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tal_dept.id
     *
     * @mbggenerated Sun Oct 15 12:33:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tal_dept.dept_name
     *
     * @mbggenerated Sun Oct 15 12:33:28 CST 2017
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tal_dept.id
     *
     * @return the value of tal_dept.id
     *
     * @mbggenerated Sun Oct 15 12:33:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tal_dept.id
     *
     * @param id the value for tal_dept.id
     *
     * @mbggenerated Sun Oct 15 12:33:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tal_dept.dept_name
     *
     * @return the value of tal_dept.dept_name
     *
     * @mbggenerated Sun Oct 15 12:33:28 CST 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tal_dept.dept_name
     *
     * @param deptName the value for tal_dept.dept_name
     *
     * @mbggenerated Sun Oct 15 12:33:28 CST 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}